name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 3 * * *'  # optional: runs daily at 3 AM UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # This was set on Github "Secrets-Variables"-"Actions"-with Arturo's API personal access token
      GITHUB_PAT: ${{ secrets.GH_PAT_ADLC }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.3.340"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("remotes","pak"), repos="https://cloud.r-project.org")'
          Rscript -e 'pak::pak(c("rmarkdown","cranlogs","knitr","stringr","tools","gh","dplyr","purrr","base64enc","commonmark","rlang","DT"), ask=FALSE)'

      - name: Run build script
        run: |
          Rscript build_data_ehm_site.R

      - name: Render site
        run: |
          quarto render

      - name: Commit and push updated docs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull --rebase origin main
          git add docs
          git diff-index --quiet HEAD || git commit -m "Auto-build site"
          git push
