# .github/workflows/deploy.yml

name: Deploy Quarto Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # --- THIS STEP HAS BEEN MODIFIED ---
      - name: Set up R and cache dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # We are now using a direct R command instead of the 'packages' keyword
          R-command: pak::local_install_dev_deps()

      - name: Run data build script
        run: Rscript build_data_ehm_site.R

      - name: Render and Deploy
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}